# -*- coding: utf-8 -*-
"""00_base_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TykxQ0pxdKcRizFFe21znuYqXWkZgBi5
"""

# ================================
# Import required libraries
# ================================

import torch
import numpy as np
import matplotlib.pyplot as plt

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# ==========================================
# Set random seeds for reproducibility
# This ensures consistent results across runs
# ==========================================

torch.manual_seed(42)
np.random.seed(42)

# ==========================================
# Load and preprocess the Fashion-MNIST dataset
# - Convert images to tensors
# - Normalize pixel values
# ==========================================

transform = transforms.Compose([
    transforms.ToTensor(),                 # Convert image to PyTorch tensor
    transforms.Normalize((0.5,), (0.5,))  # Normalize grayscale images
])

train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

print(f"Training dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")

# ==========================================
# Split the training dataset into:
# - training set
# - validation set
# ==========================================

train_size = int(0.9 * len(train_dataset))
val_size = len(train_dataset) - train_size

train_subset, val_subset = random_split(train_dataset, [train_size, val_size])

print(f"Training subset size: {len(train_subset)}")
print(f"Validation subset size: {len(val_subset)}")

# ==========================================
# Create DataLoaders for batching and shuffling
# ==========================================

batch_size = 64

train_loader = DataLoader(train_subset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_subset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print("DataLoaders created successfully.")

# ==========================================
# Visualize one sample image from the dataset
# ==========================================

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

image, label = train_dataset[0]

plt.figure(figsize=(3, 3))
plt.imshow(image.squeeze(), cmap="gray")
plt.title(f"Label: {class_names[label]}")
plt.axis("off")
plt.show()

# ==========================================
# Check image tensor shape and label format
# ==========================================

image, label = train_dataset[0]

print(f"Image tensor shape: {image.shape}")
print(f"Label index: {label}")
print(f"Class name: {class_names[label]}")



