# -*- coding: utf-8 -*-
"""01_baseline_learning_rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ClESX7m6K9L0X1I4X0xjEArwa9c5ssV
"""

# ==========================================
# Import required libraries
# ==========================================

import copy
import time
import torch
import numpy as np
import matplotlib.pyplot as plt

import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# ==========================================
# Set random seeds for reproducibility
# ==========================================

torch.manual_seed(42)
np.random.seed(42)

# ==========================================
# Select device
# ==========================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ==========================================
# Load and preprocess the Fashion-MNIST dataset
# ==========================================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

full_train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_size = int(0.9 * len(full_train_dataset))
val_size = len(full_train_dataset) - train_size

train_dataset, val_dataset = random_split(full_train_dataset, [train_size, val_size])

batch_size = 64

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Train size: {len(train_dataset)}")
print(f"Validation size: {len(val_dataset)}")
print(f"Test size: {len(test_dataset)}")

# ==========================================
# Define class labels
# ==========================================

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

# ==========================================
# Define the baseline MLP model
# Architecture: 784 -> 128 -> 64 -> 10
# ==========================================

class BaselineMLP(nn.Module):
    def __init__(self):
        super(BaselineMLP, self).__init__()

        self.network = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.network(x)

# ==========================================
# Define helper functions for training and evaluation
# ==========================================

def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == labels).sum().item()
    return correct / labels.size(0)


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()

    running_loss = 0.0
    running_acc = 0.0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        running_acc += calculate_accuracy(outputs, labels)

    epoch_loss = running_loss / len(loader)
    epoch_acc = running_acc / len(loader)

    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device):
    model.eval()

    running_loss = 0.0
    running_acc = 0.0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            running_acc += calculate_accuracy(outputs, labels)

    epoch_loss = running_loss / len(loader)
    epoch_acc = running_acc / len(loader)

    return epoch_loss, epoch_acc

# ==========================================
# Train a model for a given learning rate
# and store training history
# ==========================================

def run_experiment(learning_rate, epochs=15):
    model = BaselineMLP().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    start_time = time.time()

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(
            f"LR={learning_rate} | Epoch [{epoch+1}/{epochs}] "
            f"| Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} "
            f"| Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

    total_time = time.time() - start_time

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    results = {
        "learning_rate": learning_rate,
        "history": history,
        "test_loss": test_loss,
        "test_acc": test_acc,
        "training_time_sec": total_time,
        "model_state_dict": copy.deepcopy(model.state_dict())
    }

    return results

# ==========================================
# Run baseline experiments with different learning rates
# ==========================================

learning_rates = [0.1, 0.01, 0.001]
all_results = {}

for lr in learning_rates:
    print("\n" + "=" * 60)
    print(f"Running experiment with learning rate = {lr}")
    print("=" * 60)

    all_results[lr] = run_experiment(learning_rate=lr, epochs=15)

# ==========================================
# Plot training and validation loss curves
# for all learning rates
# ==========================================

plt.figure(figsize=(10, 6))

for lr in learning_rates:
    plt.plot(all_results[lr]["history"]["train_loss"], label=f"Train Loss (LR={lr})")
    plt.plot(all_results[lr]["history"]["val_loss"], linestyle="--", label=f"Val Loss (LR={lr})")

plt.title("Training and Validation Loss for Different Learning Rates")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# Plot validation accuracy curves
# ==========================================

plt.figure(figsize=(10, 6))

for lr in learning_rates:
    plt.plot(all_results[lr]["history"]["val_acc"], label=f"Val Acc (LR={lr})")

plt.title("Validation Accuracy for Different Learning Rates")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# Print final comparison results
# ==========================================

print("\nFinal Learning Rate Comparison")
print("-" * 70)
print(f"{'LR':<10}{'Test Loss':<15}{'Test Acc':<15}{'Train Time (s)':<15}")
print("-" * 70)

for lr in learning_rates:
    result = all_results[lr]
    print(f"{lr:<10}{result['test_loss']:<15.4f}{result['test_acc']:<15.4f}{result['training_time_sec']:<15.2f}")







