# -*- coding: utf-8 -*-
"""04_optimizer_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmJIpbCPZqlDPCho3_fhcSPFf1cSnqSb
"""

import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ======================
# Hyperparameters
# ======================
SEED = 42
BATCH_SIZE = 64
EPOCHS = 15
LR = 0.001
INPUT_SIZE = 28 * 28
HIDDEN1 = 128
HIDDEN2 = 64
NUM_CLASSES = 10

import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

transform = transforms.ToTensor()

full_train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_dataset, val_dataset = random_split(
    full_train_dataset, [54000, 6000]
)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))
print("Test size:", len(test_dataset))

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.net(x)

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

def run_experiment(optimizer_name="Adam", lr=0.001, epochs=15):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=lr)
    elif optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=lr)
    else:
        raise ValueError("Unsupported optimizer")

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(f"{optimizer_name} | Epoch [{epoch+1}/{epochs}] "
              f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} "
              f"| Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    return model, history, test_loss, test_acc

adam_model, adam_history, adam_test_loss, adam_test_acc = run_experiment(
    optimizer_name="Adam",
    lr=0.001,
    epochs=15
)

print("\nAdam Test Loss:", round(adam_test_loss, 4))
print("Adam Test Acc:", round(adam_test_acc, 4))

sgd_model, sgd_history, sgd_test_loss, sgd_test_acc = run_experiment(
    optimizer_name="SGD",
    lr=0.001,
    epochs=15
)

print("\nSGD Test Loss:", round(sgd_test_loss, 4))
print("SGD Test Acc:", round(sgd_test_acc, 4))

epochs_range = range(1, 16)

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_acc"], label="Adam Val Acc")
plt.plot(epochs_range, sgd_history["val_acc"], label="SGD Val Acc")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy Comparison")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_loss"], label="Adam Val Loss")
plt.plot(epochs_range, sgd_history["val_loss"], label="SGD Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss Comparison")
plt.legend()
plt.show()

print("Final Test Results")
print("-" * 40)
print(f"Adam | Test Loss: {adam_test_loss:.4f} | Test Acc: {adam_test_acc:.4f}")
print(f"SGD  | Test Loss: {sgd_test_loss:.4f} | Test Acc: {sgd_test_acc:.4f}")

adam_train_final = adam_history["train_acc"][-1]
adam_val_final = adam_history["val_acc"][-1]
sgd_train_final = sgd_history["train_acc"][-1]
sgd_val_final = sgd_history["val_acc"][-1]

print("\nGeneralization Gap")
print("-" * 40)
print(f"Adam | Train Acc: {adam_train_final:.4f} | Val Acc: {adam_val_final:.4f} | Gap: {adam_train_final - adam_val_final:.4f}")
print(f"SGD  | Train Acc: {sgd_train_final:.4f} | Val Acc: {sgd_val_final:.4f} | Gap: {sgd_train_final - sgd_val_final:.4f}")

# Experiment: SGD with Momentum
# This experiment evaluates the impact of momentum on the convergence behavior of SGD.
# Momentum is expected to reduce oscillations and improve optimization efficiency.

def run_experiment(optimizer_name="Adam", lr=0.001, epochs=15, momentum=0.0):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=lr)
    elif optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum)
    else:
        raise ValueError("Unsupported optimizer")

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(
            f"{optimizer_name} | Epoch [{epoch+1}/{epochs}] "
            f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | "
            f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    return model, history, test_loss, test_acc

sgdm_model, sgdm_history, sgdm_test_loss, sgdm_test_acc = run_experiment(
    optimizer_name="SGD",
    lr=0.01,
    epochs=15,
    momentum=0.9
)

print("\nSGD + Momentum Test Loss:", round(sgdm_test_loss, 4))
print("SGD + Momentum Test Acc:", round(sgdm_test_acc, 4))

epochs_range = range(1, 16)

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_acc"], label="Adam")
plt.plot(epochs_range, sgd_history["val_acc"], label="SGD")
plt.plot(epochs_range, sgdm_history["val_acc"], label="SGD + Momentum")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy Comparison")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_loss"], label="Adam")
plt.plot(epochs_range, sgd_history["val_loss"], label="SGD")
plt.plot(epochs_range, sgdm_history["val_loss"], label="SGD + Momentum")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss Comparison")
plt.legend()
plt.show()

print("Final Test Results")
print("-" * 50)
print(f"Adam           | Test Loss: {adam_test_loss:.4f} | Test Acc: {adam_test_acc:.4f}")
print(f"SGD            | Test Loss: {sgd_test_loss:.4f} | Test Acc: {sgd_test_acc:.4f}")
print(f"SGD + Momentum | Test Loss: {sgdm_test_loss:.4f} | Test Acc: {sgdm_test_acc:.4f}")

adam_train_final = adam_history["train_acc"][-1]
adam_val_final = adam_history["val_acc"][-1]

sgd_train_final = sgd_history["train_acc"][-1]
sgd_val_final = sgd_history["val_acc"][-1]

sgdm_train_final = sgdm_history["train_acc"][-1]
sgdm_val_final = sgdm_history["val_acc"][-1]

print("\nGeneralization Gap")
print("-" * 50)
print(f"Adam           | Train Acc: {adam_train_final:.4f} | Val Acc: {adam_val_final:.4f} | Gap: {adam_train_final - adam_val_final:.4f}")
print(f"SGD            | Train Acc: {sgd_train_final:.4f} | Val Acc: {sgd_val_final:.4f} | Gap: {sgd_train_final - sgd_val_final:.4f}")
print(f"SGD + Momentum | Train Acc: {sgdm_train_final:.4f} | Val Acc: {sgdm_val_final:.4f} | Gap: {sgdm_train_final - sgdm_val_final:.4f}")

import pandas as pd

results = {
    "Optimizer": ["SGD", "SGD + Momentum", "Adam"],
    "Test Accuracy": [sgd_test_acc, sgdm_test_acc, adam_test_acc]
}

df = pd.DataFrame(results)

# En iyi üste gelsin
df = df.sort_values(by="Test Accuracy", ascending=False)

df

plt.figure(figsize=(6, 4))
bars = plt.bar(df["Optimizer"], df["Test Accuracy"])

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.005, f"{yval:.3f}", ha='center')

plt.title("Optimizer Comparison (Test Accuracy)")
plt.xlabel("Optimizer")
plt.ylabel("Accuracy")
plt.ylim(0.6, 0.95)

plt.show()