# -*- coding: utf-8 -*-
"""robustness_analysis_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsoseFXJJ0mkTnZ_29L4QFnnD1ctnece
"""

# -*- coding: utf-8 -*-
"""00_base_template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TykxQ0pxdKcRizFFe21znuYqXWkZgBi5
"""

# ================================
# Import required libraries
# ================================

import torch
import numpy as np
import matplotlib.pyplot as plt

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# ==========================================
# Set random seeds for reproducibility
# This ensures consistent results across runs
# ==========================================

torch.manual_seed(42)
np.random.seed(42)

# ==========================================
# Load and preprocess the Fashion-MNIST dataset
# - Convert images to tensors
# - Normalize pixel values
# ==========================================

transform = transforms.Compose([
    transforms.ToTensor(),                 # Convert image to PyTorch tensor
    transforms.Normalize((0.5,), (0.5,))  # Normalize grayscale images
])

train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

print(f"Training dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")

# ==========================================
# Split the training dataset into:
# - training set
# - validation set
# ==========================================

train_size = int(0.9 * len(train_dataset))
val_size = len(train_dataset) - train_size

train_subset, val_subset = random_split(train_dataset, [train_size, val_size])

print(f"Training subset size: {len(train_subset)}")
print(f"Validation subset size: {len(val_subset)}")

# ==========================================
# Create DataLoaders for batching and shuffling
# ==========================================

batch_size = 64

train_loader = DataLoader(train_subset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_subset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print("DataLoaders created successfully.")

# ==========================================
# Visualize one sample image from the dataset
# ==========================================

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

image, label = train_dataset[0]

plt.figure(figsize=(3, 3))
plt.imshow(image.squeeze(), cmap="gray")
plt.title(f"Label: {class_names[label]}")
plt.axis("off")
plt.show()

# ==========================================
# Check image tensor shape and label format
# ==========================================

image, label = train_dataset[0]

print(f"Image tensor shape: {image.shape}")
print(f"Label index: {label}")
print(f"Class name: {class_names[label]}")

# -*- coding: utf-8 -*-
"""01_baseline_learning_rate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ClESX7m6K9L0X1I4X0xjEArwa9c5ssV
"""

# ==========================================
# Import required libraries
# ==========================================

import copy
import time
import torch
import numpy as np
import matplotlib.pyplot as plt

import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# ==========================================
# Set random seeds for reproducibility
# ==========================================

torch.manual_seed(42)
np.random.seed(42)

# ==========================================
# Select device
# ==========================================

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ==========================================
# Load and preprocess the Fashion-MNIST dataset
# ==========================================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

full_train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_size = int(0.9 * len(full_train_dataset))
val_size = len(full_train_dataset) - train_size

train_dataset, val_dataset = random_split(full_train_dataset, [train_size, val_size])

batch_size = 64

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"Train size: {len(train_dataset)}")
print(f"Validation size: {len(val_dataset)}")
print(f"Test size: {len(test_dataset)}")

# ==========================================
# Define class labels
# ==========================================

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

# ==========================================
# Define the baseline MLP model
# Architecture: 784 -> 128 -> 64 -> 10
# ==========================================

class BaselineMLP(nn.Module):
    def __init__(self):
        super(BaselineMLP, self).__init__()

        self.network = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.network(x)

# ==========================================
# Define helper functions for training and evaluation
# ==========================================

def calculate_accuracy(outputs, labels):
    _, predicted = torch.max(outputs, 1)
    correct = (predicted == labels).sum().item()
    return correct / labels.size(0)


def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()

    running_loss = 0.0
    running_acc = 0.0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
        running_acc += calculate_accuracy(outputs, labels)

    epoch_loss = running_loss / len(loader)
    epoch_acc = running_acc / len(loader)

    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device):
    model.eval()

    running_loss = 0.0
    running_acc = 0.0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item()
            running_acc += calculate_accuracy(outputs, labels)

    epoch_loss = running_loss / len(loader)
    epoch_acc = running_acc / len(loader)

    return epoch_loss, epoch_acc

# ==========================================
# Train a model for a given learning rate
# and store training history
# ==========================================

def run_experiment(learning_rate, epochs=15):
    model = BaselineMLP().to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=learning_rate)

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    start_time = time.time()

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(
            f"LR={learning_rate} | Epoch [{epoch+1}/{epochs}] "
            f"| Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} "
            f"| Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

    total_time = time.time() - start_time

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    results = {
        "learning_rate": learning_rate,
        "history": history,
        "test_loss": test_loss,
        "test_acc": test_acc,
        "training_time_sec": total_time,
        "model_state_dict": copy.deepcopy(model.state_dict())
    }

    return results

# ==========================================
# Run baseline experiments with different learning rates
# ==========================================

learning_rates = [0.1, 0.01, 0.001]
all_results = {}

for lr in learning_rates:
    print("\n" + "=" * 60)
    print(f"Running experiment with learning rate = {lr}")
    print("=" * 60)

    all_results[lr] = run_experiment(learning_rate=lr, epochs=15)

# ==========================================
# Plot training and validation loss curves
# for all learning rates
# ==========================================

plt.figure(figsize=(10, 6))

for lr in learning_rates:
    plt.plot(all_results[lr]["history"]["train_loss"], label=f"Train Loss (LR={lr})")
    plt.plot(all_results[lr]["history"]["val_loss"], linestyle="--", label=f"Val Loss (LR={lr})")

plt.title("Training and Validation Loss for Different Learning Rates")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# Plot validation accuracy curves
# ==========================================

plt.figure(figsize=(10, 6))

for lr in learning_rates:
    plt.plot(all_results[lr]["history"]["val_acc"], label=f"Val Acc (LR={lr})")

plt.title("Validation Accuracy for Different Learning Rates")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================
# Print final comparison results
# ==========================================

print("\nFinal Learning Rate Comparison")
print("-" * 70)
print(f"{'LR':<10}{'Test Loss':<15}{'Test Acc':<15}{'Train Time (s)':<15}")
print("-" * 70)

for lr in learning_rates:
    result = all_results[lr]
    print(f"{lr:<10}{result['test_loss']:<15.4f}{result['test_acc']:<15.4f}{result['training_time_sec']:<15.2f}")

# Step 1: Recover Ahsen's Best Baseline Model

best_lr = 0.001
baseline_model = BaselineMLP().to(device)
baseline_model.load_state_dict(all_results[best_lr]["model_state_dict"])
print("Ahsen'in Baseline modeli başarıyla yüklendi ve teste hazır!")


# Step 2: Define Gaussian Noise Function


def add_gaussian_noise(images, sigma=0.1):
    """
    Görüntülere belirlenen oranda (sigma) gürültü ekler.
    Sigma arttıkça görüntü daha kirli hale gelir.
    """

    noise = torch.randn_like(images) * sigma

    noisy_images = images + noise


    noisy_images = torch.clamp(noisy_images, -1., 1.)
    return noisy_images


# Step 3: Test Function with Noise


def evaluate_robustness(model, loader, device, sigma=0.1):
    model.eval()
    running_acc = 0.0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)


            if sigma > 0:
                images = add_gaussian_noise(images, sigma=sigma)

            outputs = model(images)


            _, predicted = torch.max(outputs, 1)
            correct = (predicted == labels).sum().item()
            running_acc += correct / labels.size(0)

    return running_acc / len(loader)


# Step 4: Run Robustness Stress Test (Baseline Only)

noise_levels = [0.0, 0.1, 0.2, 0.3, 0.4]
baseline_results = []

print("\nRobustness Stress Test: Baseline Model Analysis")
print("=" * 45)
print(f"{'Noise Sigma':<12} | {'Baseline Acc':<15}")
print("-" * 45)

for sigma in noise_levels:

    acc = evaluate_robustness(baseline_model, test_loader, device, sigma=sigma)
    baseline_results.append(acc)
    print(f"{sigma:<12.1f} | {acc:<15.4f}")


# Step 5: Visualize the Baseline Decay


plt.figure(figsize=(8, 5))
plt.plot(noise_levels, baseline_results, 'ro-', label='Baseline Model Performance')
plt.title('Impact of Gaussian Noise on Baseline Model')
plt.xlabel('Noise Level (Sigma)')
plt.ylabel('Test Accuracy')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

#betul_dropout
# -*- coding: utf-8 -*-
"""02_dropout_experiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14tYxIHumYGRx-m70XdIgeggG1C66sL3G
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
import time
import copy
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# Consistency Rules
torch.manual_seed(42)
np.random.seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Data loading (54k/6k/10k Split)
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

full_train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

# Consistent Split
train_subset, val_subset = random_split(full_train_dataset, [54000, 6000])

train_loader = DataLoader(train_subset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_subset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# MLP Architecture with Dropout
class DropoutMLP(nn.Module):
    def __init__(self, dropout_p):
        super(DropoutMLP, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.dropout1 = nn.Dropout(p=dropout_p)
        self.fc2 = nn.Linear(128, 64)
        self.dropout2 = nn.Dropout(p=dropout_p)
        self.fc3 = nn.Linear(64, 10)

    def forward(self, x):
        x = x.view(-1, 784)
        x = torch.relu(self.fc1(x))
        x = self.dropout1(x)
        x = torch.relu(self.fc2(x))
        x = self.dropout2(x)
        x = self.fc3(x)
        return x

def train_and_validate(model, train_loader, val_loader, test_loader, p_val, epochs=15, lr=0.001):
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    history = {'train_loss': [], 'val_loss': [], 'train_acc': [], 'val_acc': []}
    start_time = time.time()

    for epoch in range(epochs):
        model.train()
        t_loss, t_correct, t_total = 0, 0, 0
        for imgs, lbls in train_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, lbls)
            loss.backward()
            optimizer.step()

            t_loss += loss.item()
            _, pred = torch.max(outputs, 1)
            t_total += lbls.size(0)
            t_correct += (pred == lbls).sum().item()

        # Validation phase
        model.eval()
        v_loss, v_correct, v_total = 0, 0, 0
        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)
                outputs = model(imgs)
                v_loss += criterion(outputs, lbls).item()
                _, pred = torch.max(outputs, 1)
                v_total += lbls.size(0)
                v_correct += (pred == lbls).sum().item()

        # Store history
        train_epoch_loss = t_loss/len(train_loader)
        val_epoch_loss = v_loss/len(val_loader)
        train_epoch_acc = t_correct/t_total
        val_epoch_acc = v_correct/v_total

        history['train_loss'].append(train_epoch_loss)
        history['val_loss'].append(val_epoch_loss)
        history['train_acc'].append(train_epoch_acc)
        history['val_acc'].append(val_epoch_acc)

        # AHSEN-STYLE PRINTING
        print(f"P={p_val} | Epoch [{epoch+1}/{epochs}] | "
              f"Train Loss: {train_epoch_loss:.4f} | Train Acc: {train_epoch_acc:.4f} | "
              f"Val Loss: {val_epoch_loss:.4f} | Val Acc: {val_epoch_acc:.4f}")

    # Final Test
    model.eval()
    test_correct, test_total, test_loss = 0, 0, 0
    with torch.no_grad():
        for imgs, lbls in test_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            outputs = model(imgs)
            test_loss += criterion(outputs, lbls).item()
            _, pred = torch.max(outputs, 1)
            test_total += lbls.size(0)
            test_correct += (pred == lbls).sum().item()

    return history, test_loss/len(test_loader), test_correct/test_total, time.time() - start_time

# Run experiments
dropout_rates = [0.0, 0.2, 0.5]
results_summary = {}
histories = {}

for p in dropout_rates:
    print("\n" + "="*60)
    print(f"Running experiment with dropout p = {p}")
    print("="*60)

    model = DropoutMLP(p).to(device)
    # Note: we pass 'p' to the function now just for the print statement
    hist, t_loss, t_acc, duration = train_and_validate(model, train_loader, val_loader, test_loader, p)

    results_summary[p] = {
        'test_loss': t_loss,
        'test_acc': t_acc,
        'time': duration,
        'gap': hist['train_acc'][-1] - hist['val_acc'][-1]
    }
    histories[p] = hist

# 1. Plot Validation Accuracies
plt.figure(figsize=(15, 5))
plt.subplot(1, 3, 1)
for p in dropout_rates:
    plt.plot(histories[p]['val_acc'], label=f'p={p}')
plt.title('Validation Accuracy')
plt.legend()

# 2. Generalization Gap Plot
plt.subplot(1, 3, 2)
plt.plot(histories[0.0]['train_acc'], 'r--', label='Train (No Dropout)')
plt.plot(histories[0.0]['val_acc'], 'r', label='Val (No Dropout)')
plt.plot(histories[0.5]['train_acc'], 'g--', label='Train (p=0.5)')
plt.plot(histories[0.5]['val_acc'], 'g', label='Val (p=0.5)')
plt.title('The Generalization Gap')
plt.legend()

# 3. Validation Loss
plt.subplot(1, 3, 3)
for p in dropout_rates:
    plt.plot(histories[p]['val_loss'], label=f'p={p}')
plt.title('Validation Loss')
plt.legend()
plt.tight_layout()
plt.show()

# Final Comparison Table
print("\n" + "="*60)
print(f"{'Dropout P':<12} {'Test Acc':<12} {'Test Loss':<12} {'Gen. Gap':<12}")
print("-" * 60)
for p in dropout_rates:
    res = results_summary[p]
    print(f"{p:<12} {res['test_acc']:<12.4f} {res['test_loss']:<12.4f} {res['gap']:<12.4f}")

# Recovering Betül's Best Dropout Model


dropout_results = []

print(f"\nRobustness Stress Test: Baseline vs. Dropout (p={best_p})")
print("=" * 60)
print(f"{'Noise Sigma':<12} | {'Baseline Acc':<15} | {'Dropout Acc':<15}")
print("-" * 60)

for sigma in noise_levels:

    b_acc = baseline_results[noise_levels.index(sigma)]


    d_acc = evaluate_robustness(model, test_loader, device, sigma=sigma)
    dropout_results.append(d_acc)

    print(f"{sigma:<12.1f} | {b_acc:<15.4f} | {d_acc:<15.4f}")


# Step 2: Final Visualization (Baseline vs. Dropout)


plt.figure(figsize=(10, 6))
plt.plot(noise_levels, baseline_results, 'ro-', label='Baseline (No Regularization)')
plt.plot(noise_levels, dropout_results, 'bs-', label=f'Dropout (p={best_p})')
plt.title('Robustness Comparison: Accuracy vs. Noise Intensity')
plt.xlabel('Noise Level (Sigma)')
plt.ylabel('Test Accuracy')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# -*- coding: utf-8 -*-
"""03_L2_regularization_experiments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObWBTCfMXL9dBoWWgBq2TjmxjOuyh2IE
"""

# Imports & Setup
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
import time

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

# Reproducibility
torch.manual_seed(42)
np.random.seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Data Loading
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])

full_train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

# SAME SPLIT AS TEAM
train_subset, val_subset = random_split(full_train_dataset, [54000, 6000])

train_loader = DataLoader(train_subset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_subset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

print("Data ready.")

# Baseline MLP
class BaselineMLP(nn.Module):
    def __init__(self):
        super(BaselineMLP, self).__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.net(x)

# Training Function
def train_and_validate(weight_decay_value, epochs=15, lr=0.001):

    model = BaselineMLP().to(device)
    criterion = nn.CrossEntropyLoss()

    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=weight_decay_value)

    history = {
        'train_loss': [],
        'val_loss': [],
        'train_acc': [],
        'val_acc': []
    }

    start_time = time.time()

    for epoch in range(epochs):
        # TRAIN
        model.train()
        t_loss, t_correct, t_total = 0, 0, 0

        for imgs, lbls in train_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)

            optimizer.zero_grad()
            outputs = model(imgs)
            loss = criterion(outputs, lbls)
            loss.backward()
            optimizer.step()

            t_loss += loss.item()
            _, pred = torch.max(outputs, 1)
            t_total += lbls.size(0)
            t_correct += (pred == lbls).sum().item()

        # VALIDATION
        model.eval()
        v_loss, v_correct, v_total = 0, 0, 0

        with torch.no_grad():
            for imgs, lbls in val_loader:
                imgs, lbls = imgs.to(device), lbls.to(device)

                outputs = model(imgs)
                loss = criterion(outputs, lbls)

                v_loss += loss.item()
                _, pred = torch.max(outputs, 1)
                v_total += lbls.size(0)
                v_correct += (pred == lbls).sum().item()

        train_loss = t_loss / len(train_loader)
        val_loss = v_loss / len(val_loader)
        train_acc = t_correct / t_total
        val_acc = v_correct / v_total

        history['train_loss'].append(train_loss)
        history['val_loss'].append(val_loss)
        history['train_acc'].append(train_acc)
        history['val_acc'].append(val_acc)

        print(f"WD={weight_decay_value} | Epoch [{epoch+1}/{epochs}] | "
              f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | "
              f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")

    # TEST
    model.eval()
    test_loss, correct, total = 0, 0, 0

    with torch.no_grad():
        for imgs, lbls in test_loader:
            imgs, lbls = imgs.to(device), lbls.to(device)

            outputs = model(imgs)
            loss = criterion(outputs, lbls)

            test_loss += loss.item()
            _, pred = torch.max(outputs, 1)
            total += lbls.size(0)
            correct += (pred == lbls).sum().item()

    test_acc = correct / total

    return history, test_loss / len(test_loader), test_acc, time.time() - start_time

# Run Experiments
weight_decay_values = [0.0, 1e-4, 1e-3]

results = {}
histories = {}

for wd in weight_decay_values:
    print("\n" + "="*60)
    print(f"Running experiment with weight_decay = {wd}")
    print("="*60)

    hist, t_loss, t_acc, duration = train_and_validate(wd)

    results[wd] = {
        'test_loss': t_loss,
        'test_acc': t_acc,
        'time': duration,
        'gap': hist['train_acc'][-1] - hist['val_acc'][-1]
    }

    histories[wd] = hist

# Plots
plt.figure(figsize=(15,5))

# 1. Validation Accuracy
plt.subplot(1,3,1)
for wd in weight_decay_values:
    plt.plot(histories[wd]['val_acc'], label=f'wd={wd}')
plt.title("Validation Accuracy")
plt.legend()

# 2. Generalization Gap
plt.subplot(1,3,2)
plt.plot(histories[0.0]['train_acc'], 'r--', label='Train (No L2)')
plt.plot(histories[0.0]['val_acc'], 'r', label='Val (No L2)')
plt.plot(histories[1e-3]['train_acc'], 'g--', label='Train (wd=1e-3)')
plt.plot(histories[1e-3]['val_acc'], 'g', label='Val (wd=1e-3)')
plt.title("Generalization Gap")
plt.legend()

# 3. Validation Loss
plt.subplot(1,3,3)
for wd in weight_decay_values:
    plt.plot(histories[wd]['val_loss'], label=f'wd={wd}')
plt.title("Validation Loss")
plt.legend()

plt.tight_layout()
plt.show()

# Final Table
print("\n" + "="*60)
print(f"{'Weight Decay':<15}{'Test Acc':<15}{'Test Loss':<15}{'Gen Gap':<15}")
print("-"*60)

for wd in weight_decay_values:
    res = results[wd]
    print(f"{wd:<15}{res['test_acc']:<15.4f}{res['test_loss']:<15.4f}{res['gap']:<15.4f}")

# Baseline vs. Dropout vs. L2 (Weight Decay)



best_wd = 1e-4
l2_model = BaselineMLP().to(device)


l2_model = model

l2_results = []

print(f"\nFinal Stress Test: Comparison of All Regularization Techniques")
print("=" * 75)
print(f"{'Noise Sigma':<12} | {'Baseline Acc':<13} | {'Dropout Acc':<13} | {'L2 Acc':<13}")
print("-" * 75)

for sigma in noise_levels:

    b_acc = baseline_results[noise_levels.index(sigma)]
    d_acc = dropout_results[noise_levels.index(sigma)]


    l_acc = evaluate_robustness(l2_model, test_loader, device, sigma=sigma)
    l2_results.append(l_acc)

    print(f"{sigma:<12.1f} | {b_acc:<13.4f} | {d_acc:<13.4f} | {l_acc:<13.4f}")

# Step 2: Final Triple Visualization


plt.figure(figsize=(12, 7))
plt.plot(noise_levels, baseline_results, 'ro-', label='Baseline (No Reg)')
plt.plot(noise_levels, dropout_results, 'bs-', label=f'Dropout (p={best_p})')
plt.plot(noise_levels, l2_results, 'g^-', label=f'L2 Regularization (wd={best_wd})')

plt.title('The Ultimate Robustness Battle: Accuracy vs. Noise Intensity', fontsize=14)
plt.xlabel('Noise Level (Sigma)', fontsize=12)
plt.ylabel('Test Accuracy', fontsize=12)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# -*- coding: utf-8 -*-
"""04_optimizer_comparison.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmJIpbCPZqlDPCho3_fhcSPFf1cSnqSb
"""

import torch

print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ======================
# Hyperparameters
# ======================
SEED = 42
BATCH_SIZE = 64
EPOCHS = 15
LR = 0.001
INPUT_SIZE = 28 * 28
HIDDEN1 = 128
HIDDEN2 = 64
NUM_CLASSES = 10

import random
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim

from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

transform = transforms.ToTensor()

full_train_dataset = datasets.FashionMNIST(
    root="./data",
    train=True,
    download=True,
    transform=transform
)

test_dataset = datasets.FashionMNIST(
    root="./data",
    train=False,
    download=True,
    transform=transform
)

train_dataset, val_dataset = random_split(
    full_train_dataset, [54000, 6000]
)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

print("Train size:", len(train_dataset))
print("Val size:", len(val_dataset))
print("Test size:", len(test_dataset))

class_names = [
    "T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
    "Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"
]

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.net(x)

def train_one_epoch(model, loader, criterion, optimizer, device):
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc


def evaluate(model, loader, criterion, device):
    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in loader:
            images, labels = images.to(device), labels.to(device)

            outputs = model(images)
            loss = criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, predicted = torch.max(outputs, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    return epoch_loss, epoch_acc

def run_experiment(optimizer_name="Adam", lr=0.001, epochs=15):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=lr)
    elif optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=lr)
    else:
        raise ValueError("Unsupported optimizer")

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(f"{optimizer_name} | Epoch [{epoch+1}/{epochs}] "
              f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} "
              f"| Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}")

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    return model, history, test_loss, test_acc

adam_model, adam_history, adam_test_loss, adam_test_acc = run_experiment(
    optimizer_name="Adam",
    lr=0.001,
    epochs=15
)

print("\nAdam Test Loss:", round(adam_test_loss, 4))
print("Adam Test Acc:", round(adam_test_acc, 4))

sgd_model, sgd_history, sgd_test_loss, sgd_test_acc = run_experiment(
    optimizer_name="SGD",
    lr=0.001,
    epochs=15
)

print("\nSGD Test Loss:", round(sgd_test_loss, 4))
print("SGD Test Acc:", round(sgd_test_acc, 4))

epochs_range = range(1, 16)

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_acc"], label="Adam Val Acc")
plt.plot(epochs_range, sgd_history["val_acc"], label="SGD Val Acc")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy Comparison")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_loss"], label="Adam Val Loss")
plt.plot(epochs_range, sgd_history["val_loss"], label="SGD Val Loss")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss Comparison")
plt.legend()
plt.show()

print("Final Test Results")
print("-" * 40)
print(f"Adam | Test Loss: {adam_test_loss:.4f} | Test Acc: {adam_test_acc:.4f}")
print(f"SGD  | Test Loss: {sgd_test_loss:.4f} | Test Acc: {sgd_test_acc:.4f}")

adam_train_final = adam_history["train_acc"][-1]
adam_val_final = adam_history["val_acc"][-1]
sgd_train_final = sgd_history["train_acc"][-1]
sgd_val_final = sgd_history["val_acc"][-1]

print("\nGeneralization Gap")
print("-" * 40)
print(f"Adam | Train Acc: {adam_train_final:.4f} | Val Acc: {adam_val_final:.4f} | Gap: {adam_train_final - adam_val_final:.4f}")
print(f"SGD  | Train Acc: {sgd_train_final:.4f} | Val Acc: {sgd_val_final:.4f} | Gap: {sgd_train_final - sgd_val_final:.4f}")

# Experiment: SGD with Momentum
# This experiment evaluates the impact of momentum on the convergence behavior of SGD.
# Momentum is expected to reduce oscillations and improve optimization efficiency.

def run_experiment(optimizer_name="Adam", lr=0.001, epochs=15, momentum=0.0):
    model = MLP().to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == "Adam":
        optimizer = optim.Adam(model.parameters(), lr=lr)
    elif optimizer_name == "SGD":
        optimizer = optim.SGD(model.parameters(), lr=lr, momentum=momentum)
    else:
        raise ValueError("Unsupported optimizer")

    history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": []
    }

    for epoch in range(epochs):
        train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, device)
        val_loss, val_acc = evaluate(model, val_loader, criterion, device)

        history["train_loss"].append(train_loss)
        history["train_acc"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_acc"].append(val_acc)

        print(
            f"{optimizer_name} | Epoch [{epoch+1}/{epochs}] "
            f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.4f} | "
            f"Val Loss: {val_loss:.4f} | Val Acc: {val_acc:.4f}"
        )

    test_loss, test_acc = evaluate(model, test_loader, criterion, device)

    return model, history, test_loss, test_acc

sgdm_model, sgdm_history, sgdm_test_loss, sgdm_test_acc = run_experiment(
    optimizer_name="SGD",
    lr=0.01,
    epochs=15,
    momentum=0.9
)

print("\nSGD + Momentum Test Loss:", round(sgdm_test_loss, 4))
print("SGD + Momentum Test Acc:", round(sgdm_test_acc, 4))

epochs_range = range(1, 16)

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_acc"], label="Adam")
plt.plot(epochs_range, sgd_history["val_acc"], label="SGD")
plt.plot(epochs_range, sgdm_history["val_acc"], label="SGD + Momentum")
plt.xlabel("Epoch")
plt.ylabel("Validation Accuracy")
plt.title("Validation Accuracy Comparison")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot(epochs_range, adam_history["val_loss"], label="Adam")
plt.plot(epochs_range, sgd_history["val_loss"], label="SGD")
plt.plot(epochs_range, sgdm_history["val_loss"], label="SGD + Momentum")
plt.xlabel("Epoch")
plt.ylabel("Validation Loss")
plt.title("Validation Loss Comparison")
plt.legend()
plt.show()

print("Final Test Results")
print("-" * 50)
print(f"Adam           | Test Loss: {adam_test_loss:.4f} | Test Acc: {adam_test_acc:.4f}")
print(f"SGD            | Test Loss: {sgd_test_loss:.4f} | Test Acc: {sgd_test_acc:.4f}")
print(f"SGD + Momentum | Test Loss: {sgdm_test_loss:.4f} | Test Acc: {sgdm_test_acc:.4f}")

adam_train_final = adam_history["train_acc"][-1]
adam_val_final = adam_history["val_acc"][-1]

sgd_train_final = sgd_history["train_acc"][-1]
sgd_val_final = sgd_history["val_acc"][-1]

sgdm_train_final = sgdm_history["train_acc"][-1]
sgdm_val_final = sgdm_history["val_acc"][-1]

print("\nGeneralization Gap")
print("-" * 50)
print(f"Adam           | Train Acc: {adam_train_final:.4f} | Val Acc: {adam_val_final:.4f} | Gap: {adam_train_final - adam_val_final:.4f}")
print(f"SGD            | Train Acc: {sgd_train_final:.4f} | Val Acc: {sgd_val_final:.4f} | Gap: {sgd_train_final - sgd_val_final:.4f}")
print(f"SGD + Momentum | Train Acc: {sgdm_train_final:.4f} | Val Acc: {sgdm_val_final:.4f} | Gap: {sgdm_train_final - sgdm_val_final:.4f}")

import pandas as pd

results = {
    "Optimizer": ["SGD", "SGD + Momentum", "Adam"],
    "Test Accuracy": [sgd_test_acc, sgdm_test_acc, adam_test_acc]
}

df = pd.DataFrame(results)


df = df.sort_values(by="Test Accuracy", ascending=False)

df

plt.figure(figsize=(6, 4))
bars = plt.bar(df["Optimizer"], df["Test Accuracy"])

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.005, f"{yval:.3f}", ha='center')

plt.title("Optimizer Comparison (Test Accuracy)")
plt.xlabel("Optimizer")
plt.ylabel("Accuracy")
plt.ylim(0.6, 0.95)

plt.show()

# Baseline vs. Dropout vs. L2 vs. Best Optimizer



hacer_results = []

print(f"\nGRAND FINAL: Complete Team Robustness Analysis")
print("=" * 100)
print(f"{'Sigma':<8} | {'Baseline':<12} | {'Dropout':<12} | {'L2 (Süreyya)':<13} | {'Adam (Hacer)':<12}")
print("-" * 100)

for sigma in noise_levels:
    # Önceki arkadaşların sonuçlarını listelerden alıyoruz
    b_acc = baseline_results[noise_levels.index(sigma)]
    d_acc = dropout_results[noise_levels.index(sigma)]
    l_acc = l2_results[noise_levels.index(sigma)]


    h_acc = evaluate_robustness(adam_model, test_loader, device, sigma=sigma)
    hacer_results.append(h_acc)

    print(f"{sigma:<8.1f} | {b_acc:<12.4f} | {d_acc:<12.4f} | {l_acc:<13.4f} | {h_acc:<12.4f}")


# Step 3: Final Team Visualization

plt.figure(figsize=(14, 8))
plt.plot(noise_levels, baseline_results, 'ro-', label='Baseline ')
plt.plot(noise_levels, dropout_results, 'bs-', label=f'Dropout ( p={best_p})')
plt.plot(noise_levels, l2_results, 'g^-', label=f'L2 Reg ( wd={best_wd})')
plt.plot(noise_levels, hacer_results, 'm*-', label='Adam Optimizer')

plt.title('FashionMNIST: Final Team Robustness Comparison', fontsize=16)
plt.xlabel('Gaussian Noise Level (Sigma)', fontsize=14)
plt.ylabel('Test Accuracy', fontsize=14)
plt.legend()
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()